In [18]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
from scipy.io import loadmat
import warnings
warnings.filterwarnings('ignore')

In [19]:
#loading all data
control_turbulence = loadmat('Turbulence Output/Control Turbulence Profile.mat')['turbulence_values'].flatten()
low_turbulence = loadmat('Turbulence Output/Low Dens Turbulence Profile.mat')['turbulence_values'].flatten()
medium_turbulence = loadmat('Turbulence Output/Medium Dens Turbulence Profile.mat')['turbulence_values'].flatten()
high_turbulence = loadmat('Turbulence Output/High Dens Turbulence Profile.mat')['turbulence_values'].flatten()

In [20]:
control_table = pd.DataFrame(columns = ['Height (cm)', 'Re = 68.15', 'Re = 133.59', 'Re = 199.03'])
control_table['Height (cm)'] = [6.7]*3 + [14.77]*3 + [24.9]*3 + [36.1]*3
low_table = pd.DataFrame(columns = ['Height (cm)', 'Re = 68.15', 'Re = 133.59', 'Re = 199.03'])
low_table['Height (cm)'] = [6.7]*3 + [14.77]*3 + [24.9]*3 + [36.1]*3
medium_table = pd.DataFrame(columns = ['Height (cm)', 'Re = 68.15', 'Re = 133.59', 'Re = 199.03'])
medium_table['Height (cm)'] = [6.7]*3 + [14.77]*3 + [24.9]*3 + [36.1]*3
high_table = pd.DataFrame(columns = ['Height (cm)', 'Re = 68.15', 'Re = 133.59', 'Re = 199.03'])
high_table['Height (cm)'] = [6.7]*3 + [14.77]*3 + [24.9]*3 + [36.1]*3

indices = np.arange(0,24,2)
control_turbulence = control_turbulence[indices]
low_turbulence = low_turbulence[indices]
medium_turbulence = medium_turbulence[indices]
high_turbulence = high_turbulence[indices]

In [21]:
#this function extracts individual turbulence values
def extract_turbulence_values(array):
    triple = []
    for k in range(len(array)):
        triple.append(round(array[k][0],8))
    return triple

def populate_table(table, data):
    for i in range(table.shape[0]):
        turb_values = extract_turbulence_values(data[i])
        for j in range(3):
            table.iloc[i:i+1, j+1:j+2] = turb_values[j]
    low = table.groupby('Height (cm)')['Re = 68.15'].apply(np.array)
    med = table.groupby('Height (cm)')['Re = 133.59'].apply(np.array)
    hig = table.groupby('Height (cm)')['Re = 199.03'].apply(np.array)
    return pd.concat([low, med, hig], axis = 1)

In [22]:
control_table = populate_table(control_table, control_turbulence)
low_table = populate_table(low_table, low_turbulence)
medium_table = populate_table(medium_table, medium_turbulence)
high_table = populate_table(high_table, high_turbulence)
all_values = pd.concat([control_table, low_table, medium_table, high_table])

In [23]:
first_index = [0]*4 + [0.88]*4 + [2.54]*4 + [4.6]*4
all_values['Frontal Area $(m^{-1})$'] = first_index
all_values = all_values.reset_index()
all_values.set_index(['Frontal Area $(m^{-1})$', 'Height (cm)'])

                                                            Re = 68.15  \
Frontal Area $(m^{-1})$ Height (cm)
0.00                    6.70          [1.79e-06, 1.727e-05, 1.885e-05]
                        14.77            [2.6e-06, 3.03e-06, 3.39e-06]
                        24.90            [2.14e-06, 3.2e-06, 2.31e-06]
                        36.10                 [nan, 4.4e-06, 5.84e-06]
0.88                    6.70           [2.43e-06, 4.93e-06, 4.579e-05]
                        14.77          [1.27e-06, 5.36e-06, 1.251e-05]
                        24.90          [4.09e-06, 7.81e-06, 1.367e-05]
                        36.10          [2.83e-06, 4.89e-06, 7.863e-05]
2.54                    6.70         [1.095e-05, 2.919e-05, 3.521e-05]
                        14.77         [9.36e-06, 3.572e-05, 6.105e-05]
                        24.90        [1.077e-05, 3.701e-05, 6.676e-05]
                        36.10                    [nan, nan, 6.232e-05]
4.60                    6.70            [6.77e-06, 3.3e-05, 7.855e-05]
                        14.77        [1.154e-05, 3.034e-05, 5.538e-05]
                        24.90         [7.81e-06, 2.598e-05, 4.443e-05]
                        36.10         [5.64e-06, 2.272e-05, 4.373e-05]

                                                           Re = 133.59  \
Frontal Area $(m^{-1})$ Height (cm)
0.00                    6.70          [2.09e-06, 1.805e-05, 1.964e-05]
                        14.77           [2.43e-06, 2.93e-06, 3.33e-06]
                        24.90           [2.43e-06, 3.27e-06, 2.28e-06]
                        36.10                [nan, 4.33e-06, 5.81e-06]
0.88                    6.70           [2.01e-06, 5.13e-06, 6.253e-05]
                        14.77           [1.2e-06, 5.23e-06, 1.207e-05]
                        24.90          [4.16e-06, 7.26e-06, 1.291e-05]
                        36.10           [2.74e-06, 4.67e-06, 7.22e-05]
2.54                    6.70         [1.116e-05, 2.846e-05, 3.391e-05]
                        14.77         [9.21e-06, 3.598e-05, 5.929e-05]
                        24.90        [1.183e-05, 3.852e-05, 7.158e-05]
                        36.10                     [nan, nan, 6.07e-05]
4.60                    6.70           [6.6e-06, 3.124e-05, 7.446e-05]
                        14.77        [1.094e-05, 2.929e-05, 5.193e-05]
                        24.90         [7.82e-06, 2.485e-05, 4.269e-05]
                        36.10         [5.28e-06, 2.206e-05, 4.212e-05]

                                                           Re = 199.03
Frontal Area $(m^{-1})$ Height (cm)
0.00                    6.70           [1.94e-06, 1.849e-05, 2.09e-05]
                        14.77           [2.41e-06, 2.99e-06, 3.38e-06]
                        24.90           [2.49e-06, 3.17e-06, 2.23e-06]
                        36.10                [nan, 4.52e-06, 5.77e-06]
0.88                    6.70           [1.94e-06, 5.89e-06, 7.256e-05]
                        14.77          [1.23e-06, 5.18e-06, 1.212e-05]
                        24.90           [4.15e-06, 7.11e-06, 1.28e-05]
                        36.10          [2.74e-06, 4.76e-06, 6.694e-05]
2.54                    6.70          [1.148e-05, 2.916e-05, 3.54e-05]
                        14.77          [8.81e-06, 3.608e-05, 5.86e-05]
                        24.90           [1.13e-05, 3.6e-05, 6.991e-05]
                        36.10                    [nan, nan, 5.621e-05]
4.60                    6.70          [6.75e-06, 3.175e-05, 7.546e-05]
                        14.77        [1.088e-05, 2.984e-05, 5.594e-05]
                        24.90          [8.01e-06, 2.55e-05, 4.363e-05]
                        36.10          [5.4e-06, 2.341e-05, 4.291e-05]

In [24]:
all_values.to_csv('all_turbulence_values')